### ISSUE TITLE
mesh generate

### ISSUE THREAD

**Issue by JACKYLUO1991** [huangyangyi/ELICIT#1]
Thanks for open source, I'm interested in mesh generation, will this part be open source at some point in the future?

**Comment by JACKYLUO1991** [comment]
@huangyangyi  The training process often shows 100% GPU utilization and the code gets stuck...

**Comment by huangyangyi** [comment]
We support mesh generation in the current as an experimental feature. Using `fashion/fs4235_m394` as an example, you can add the following configs to `finetune.yaml`.
```yaml
mesh:
  dataset_module: 'core.data.human_nerf.mesh'
  dataset: 'fashion_fs4235_m394_test'
  render_gt_view: True
```
And run `python run.py --type mesh --cfg $YOUR_CONFIG` to generate the mesh.
We are still working on extracting better meshes from the NeRF model. For the training problem, please open a new issue and provide more details in it to help us debug.
